### ISSUE TITLE
Accept multiple EPIs/SBRefs for reference image calculation

### ISSUE THREAD

**Issue by tsalo** [nipreps/niworkflows#399]
`init_bold_reference_wf` currently accepts a single SBRef image and a single EPI run. With multi-echo EPI, however, there will generally be one SBRef and one EPI run for each echo. The current idea for fMRIPrep is to use just the first echo's SBRef/EPI as the reference image, but I think that it's likely that at some point some method will be developed that leverages the information across echoes. Therefore, it might be good to make sure that `init_bold_reference_wf` can accept a list of EPI/SBRef images, even if it just selects the first image internally for now.

This references https://github.com/poldracklab/fmriprep/issues/1745#issuecomment-533629602.

**Comment by emdupre** [comment]
Just wanted to :+1:  -- this approach makes sense to me !
