### ISSUE TITLE
Excessive saved artifacts

### ISSUE THREAD

**Issue by effigies** [nipreps/niworkflows#406]
It takes 10 minutes to upload artifacts, and another 3-4 to upload the same directory to "test results". We should figure out what we want uploaded where, and prune anything that isn't worth looking at.

**Comment by oesteban** [comment]
I think the intent was to have enough materials for debugging in case of failures. We could just stick in a deletion step that is run only when all tests have passed so far.

**Comment by effigies** [comment]
I feel like there's just a lot there. Surely we can delete much of it without losing debug capabilities. I just don't feel up to looking at it alone, since there's so much in here that others might find important.

**Comment by effigies** [comment]
I feel like there's just a lot there. Surely we can delete much of it without losing debug capabilities. I just don't feel up to looking at it alone, since there's so much in here that others might find important.

**Comment by oesteban** [comment]
Now down to ~10s in both test_masks and test_pytest builds.
