### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by effigies** [nipreps/niworkflows#431]
With 1.0, it would probably be good to finally move to a proper semantic versioning. i.e., API changes (new features, deprecations) should only happen on minor releases, and patch releases should be specifically for bug fixes.

This will take a bit more discipline with our PRs, potentially maintaining a feature and a bug-fix branch simultaneously, but hopefully it will help avoid situations where the different downstream projects leapfrog each other with API changes.

**Comment by effigies** [comment]
#417 is going to require a 1.1.0 release because it changes the API, causing a breakage for @jdkent in https://circleci.com/gh/jdkent/fmriprep/658.

I'm going to create a `maint/1.0.x` branch and cherry-pick #432 and #438.

**Comment by effigies** [comment]
FTR:

```
git fetch upstream
git checkout 1.0.0 -b maint/1.0.x
git cherry-pick 756cd7f7 84c99d6d 748e7269
git push upstream maint/1.0.x
git checkout master  # I keep mine synced with upstream, not origin
git pull
git merge maint/1.0.x
git push upstream maint/1.0.x master
```

**Comment by effigies** [comment]
Created "api change", "new feature" and "backwards compatible" labels. The first two should always go into master and trigger a new minor release. The latter *may* squeeze into a bugfix release just because things won't get broken.

**Comment by jdkent** [comment]
So this the power of `git`

![Darth Markiewicz The Wise](https://i.imgflip.com/3irlyr.jpg "Darth Markiewicz The Wise")

> Created "api change", "new feature" and "backwards compatible" labels. The first two should always go into master and trigger a new minor release.

Just to see if I understand correctly. Let's say fmriprep is using niworkflows `1.0.1`, and several new features are added to niworkflows, bumping the version to `1.2.0`. If someone reports a bug and `fmriprep` is still using niworkflows `1.0.1`, would we apply the bug fix on top of `1.0.1` tag commit and release `1.0.2`, and then see if the bug fix can applied to the other minor releases as well?

**Comment by effigies** [comment]
@jdkent Yes. By putting bug fixes that don't change the API on a maintenance branch, we can simplify the fMRIPrep bug-fix release process substantially. When there's an API change that is not yet accounted for in fMRIPrep, then bug fixes are harder to test.

**Comment by oesteban** [comment]
Is there any action left to be done here?

**Comment by jdkent** [comment]
unless we want to document this workflow somewhere, I think this issue can be closed.
