### ISSUE TITLE
should figures.json have dwi as datatype?

### ISSUE THREAD

**Issue by jdkent** [nipreps/niworkflows#444]
In [figures.json](https://github.com/poldracklab/niworkflows/blob/7a375031a83f5fd8ee63a78ef301bea50f29575a/niworkflows/reports/figures.json#L116), should there be `dwi` option in `default_paths`? Currently only looks like anatomical and functional images are supported.

**Comment by oesteban** [comment]
I don't think those default_paths are being used anywhere yet, but from a theoretical perspective - yes they should.

**Comment by jdkent** [comment]
thanks @oesteban! This was a red herring as I was making a solution for #443.

**Comment by oesteban** [comment]
Addressed with #507
