### ISSUE TITLE
ResampleImageBySpacing causing unintended flip

### ISSUE THREAD

**Issue by eilidhmacnicol** [nipreps/niworkflows#459]
ResampleImageBySpacing caused an AP and LR flip, due to ANTs handling of nifti header - as in #433 

![image](https://user-images.githubusercontent.com/54267723/74273399-4352f580-4cc5-11ea-95c9-a42dcc055630.png)

**Comment by oesteban** [comment]
Will be resolved directly on the interface upstreamed to NiPype
