### ISSUE TITLE
Transfer to nipreps/ org

### ISSUE THREAD

**Issue by oesteban** [nipreps/niworkflows#462]
As for SDCFlows and sMRIPrep - ready to make the move?

**Comment by effigies** [comment]
I vote for waiting until after the 20.0.0 release. No need to fiddle with the process between now and then.

**Comment by oesteban** [comment]
Sure, no problem with that. I was just thinking that splitting circle builds between nipreps and poldracklab would give us some extra agility. But I'm good either way.

**Comment by effigies** [comment]
True. I just don't want to find we haven't copied the right environment variables and only find out on a tag while we're trying to rush out a quick fix.

**Comment by oesteban** [comment]
Green lights?

**Comment by effigies** [comment]
Sure.
