### ISSUE TITLE
merge maint/1.1x into master?

### ISSUE THREAD

**Issue by jdkent** [nipreps/niworkflows#480]
For each release, are we merging the current maint branch into master, or what are the rules we should be applying?

[maint/1.1.x](https://github.com/nipreps/niworkflows/tree/maint/1.1.x) is currently 7 commits ahead of [master](https://github.com/nipreps/niworkflows/tree/master)

**Comment by effigies** [comment]
Maintenance branches may be merged into master as it seems useful.

**Comment by jdkent** [comment]
thanks! then I should have opened my pull request #479 against maint/1.1.x anyways since it is a bug fix and not a feature. I'll get that straightened out.
