### ISSUE TITLE
Artifacts in mosaic plots when intersection of masks and visualization planes is minimal

### ISSUE THREAD

**Issue by oesteban** [nipreps/niworkflows#542]
This problem has been around for a long while. When the intersection of the mask with the visualization plane only contains a fraction of a voxel, nilearn plotting gets very confused:

<img src="https://5825-53608443-gh.circle-artifacts.com/0/tmp/ds054/derivatives/fmriprep/sub-100185/figures/sub-100185_task-machinegame_run-2_desc-rois_bold.svg" />

With poldracklab/fmriprep#2130 the problem is exacerbated (not so much for fully sampled datasets, but definitely for our test data).

I believe this problem would completely be fixed if we replaced the affine information of the input images to be aligned with the cardinal axes. To do so, I'd propose:

1. `nibabel.as_closest_canonical` to all volumetric inputs of plots.
2. Generate a new affine with: image_zooms x identity
3. Perhaps re-center the volume for visualization purposes (so reported coordinates are w.r.t. the center of the volume).

This way, visualization will cut through full voxels always and the marching cubes algorithm will not go bananas.

In general, this approach would also make our reports more transparent because:
1. We would be able to safely drop interpolations by nilearn
2. The user will have access to the visualization of the naked data array, instead of a reoriented version.

Opinions?

**Comment by oesteban** [comment]
This is another manifestation of #281 which escapes the solution in #304 because the glitch does not only happen at views on the edge of the brain.

**Comment by effigies** [comment]
Probably better to comment here than on #544. So the issue, to be clear, is that nilearn can't handle images that do not have identical affine and FoV? Or can't handle oblique images?

**Comment by oesteban** [comment]
The second, nilearn trips when these three happen together:

- Plotting with `add_contour()`
- Contour (mask) has sparse voxels
- Oblique affine
