### ISSUE TITLE
Move between displayed images in Jupyter Notebook

### ISSUE THREAD

**Issue by lilikapa** [nipreps/niworkflows#546]
Dear Nipreps team,

Could you please point me out how can I move and interact with the displayed images in Jupyter Notebook? For example, if a display the reference (F) and moving (M) images, how can I switch between images to see if they are aligned.

Many thanks in advance!

**Comment by oesteban** [comment]
If you are using this utility:

https://github.com/nipreps/niworkflows/blob/cf1f227dfa8495c51c821e9d6fc04a80730ec0d4/niworkflows/viz/notebook.py#L8-L15

(which I assume you are using) - then you just need to hover your mouse over the panel. Sometimes the browser might be a bit overloaded and clicking on the mosaic may help.

**Comment by oesteban** [comment]
Please reopen if I didn't correctly answer your question.
