### ISSUE TITLE
MultiApplyTransforms does not support `identity` transform in list

### ISSUE THREAD

**Issue by emdupre** [nipreps/niworkflows#553]
Discovered in https://github.com/poldracklab/fmriprep/pull/2239

Here's a reproducible example, assuming you have a toy 'affine.txt' file locally:

```python
> from niworkflows.interfaces import itk  

> bold_to_t1_transform = itk.MultiApplyTransforms()
> bold_to_t1_transform.inputs.transforms = ['./affine.txt', './affine.txt']  # OK
> bold_to_t1_transform.inputs.transforms = 'identity'  # OK
> bold_to_t1_transform.inputs.transforms = ['identity', './affine.txt']  # Fails

TraitError: The 'transforms' trait of a _MultiApplyTransformsInputSpec instance must be a list of items which are a pathlike object or string representing an existing file or 'identity', but a value of ['identity', './affine.txt'] <class 'list'> was specified.
```

A transform of `['identity', 'identity']` fails similarly. I can look into this tonight.

**Comment by effigies** [comment]
I'm taking a shot at this now.

**Comment by effigies** [comment]
Annoyingly, the bug here is a Nipype problem. If we pass `identity` to regular `ApplyTransforms`, we may need to patch that, too.

**Comment by oesteban** [comment]
There were concerns that led to not implementing the identity because it's not documented. But yes, this pertains in nipype's proper.
