### ISSUE TITLE
Building docs takes >40 minutes on master

### ISSUE THREAD

**Issue by effigies** [nipreps/niworkflows#557]
Can we reuse prior builds to avoid building all old versions every time?

**Comment by effigies** [comment]
Example run: https://app.circleci.com/pipelines/github/nipreps/niworkflows/398/workflows/1f3e62ab-c67d-4a13-bd70-7aa46fe1d5b0/jobs/1862

**Comment by oesteban** [comment]
Yeah, this is getting very bad. I believe sphinxcontrib-versioning should actually not build old releases if they are already built - however it is clearly not working.

**Comment by effigies** [comment]
Is there any advantage to keeping old commits around? I suspect it's `gh-pages` that's making clones take 1.7 minutes.

**Comment by oesteban** [comment]
I think that's one problem - probably solvable with a shallow clone that only fetches master and tags.

I don't think sphinxcontrib-versioning is building old commits, I think it is just building all tags.

**Comment by effigies** [comment]
But there's no real advantage to keeping history. I would suggest just squashing everything down to a single commit periodically (or even on every build) so that garbage collection can do its work.

**Comment by effigies** [comment]
History squashed with #622. Still need to build off of the last commit to save time.

**Comment by oesteban** [comment]
I just added the `bug` label because I think we are not reusing the existing documents in the gh-pages branch, and hence all the versions are built all the times.

I'm not confident the sphinxcontrib-versioning will reuse them (the package is pretty buggy), but, it will certainly will not if they are just not available :D
