### ISSUE TITLE
DerivativesDataSink shows warning when it has multiple source files

### ISSUE THREAD

**Issue by HippocampusGirl** [nipreps/niworkflows#572]
### What version of fMRIPrep are you using?
20.2.0

### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"?
Singularity

When running the latest version of fmriprep, I receive a lot of warnings of the form

```
[WARNING  ] Could not get data type of file ['.../ds000102/sub-06/func/sub-06_task-flanker_run-1_bold.nii.gz']
```

I tracked this warning to DerivativesDatasink:

https://github.com/nipreps/niworkflows/blob/22db00afa338d3c76ee5ea45a26826a17ba53e89/niworkflows/interfaces/bids.py#L617-L624

It appears as though DerivativesDatasink was changed for release 1.3.1 to accept a list for the input `source_file`, but the call to `nibabel.load` on line 619 does not work with a list, throwing the exception

```
TypeError: stat: path should be string, bytes, os.PathLike or integer, not list
```

Are you seeing the same warnings? Is this the intended behavior?

Thank you for your help :-)

**Comment by oesteban** [comment]
This definitely looks like an oversight when we merged #547. Thanks for catching this - and always open to take contributions ;)
