### ISSUE TITLE
MemoryError in `init_bold_reference_wf` `gen_ref`

### ISSUE THREAD

**Issue by HippocampusGirl** [nipreps/niworkflows#628]
@ilyaveer and I have encountered a MemoryError in `init_bold_reference_wf` with version 1.3.2, when the bold file is very large (multiband data).
```
MemoryError: Unable to allocate 4.23 GiB for an array with shape (97, 115, 97, 525) and data type float64
```
[crash-20210409-151708-yansch-gen_ref.a0-ee823608-df22-40e4-84d8-fb225777e3d8.txt](https://github.com/nipreps/niworkflows/files/6308806/crash-20210409-151708-yansch-gen_ref.a0-ee823608-df22-40e4-84d8-fb225777e3d8.txt)

After looking at the code, I believe the problem may be that `gen_ref` (1.3.2) and its successor `gen_avg` (1.4.0rc5) are coded to have a memory usage of at most one gigabyte. 
https://github.com/nipreps/niworkflows/blob/dafdb2e21242337527a2fd91a8e358f6a37a564c/niworkflows/func/util.py#L156-L158 https://github.com/nipreps/niworkflows/blob/616d2bca69c023a4144afe3d1117b9c3ef5ebbcd/niworkflows/func/util.py#L168

However, when running, the interface `RobustAverage` (and its predecessor `EstimateReferenceImage`) both load the entire bold_file into memory, which may in some cases use much more than one gigabyte.
https://github.com/nipreps/niworkflows/blob/616d2bca69c023a4144afe3d1117b9c3ef5ebbcd/niworkflows/interfaces/images.py#L227

As such, I was wondering whether it would be possible to make the `mem_gb` adaptive as is done in other places, so that memory errors can be avoided by the nipype scheduler. This would likely entail adding a parameter to `init_bold_reference_wf`. I would be happy to contribute code.

**Comment by effigies** [comment]
Looks like the problem is that we're loading whole files here:

https://github.com/nipreps/niworkflows/blob/4d9b741d2dbd3bc3d434e6b8db45e58cab14fc18/niworkflows/interfaces/registration.py#L485-L491

And then dropping them later:

https://github.com/nipreps/niworkflows/blob/4d9b741d2dbd3bc3d434e6b8db45e58cab14fc18/niworkflows/interfaces/registration.py#L516-L541

We never use more than the first 40 volumes, so we should never allocate more, and stop accumulating once we have 40 volumes.

**Comment by oesteban** [comment]
@HippocampusGirl - have you been able to test the fix?

**Comment by HippocampusGirl** [comment]
> @HippocampusGirl - have you been able to test the fix?

No, I haven't heard back from my colleague yet. I guess that means good news :-) But I will keep you updated.
