### ISSUE TITLE
DerivativesDataSink not preventing gzip mtime from being set, leading to non-deterministic file checksums

### ISSUE THREAD

**Issue by effigies** [nipreps/niworkflows#640]
As reported by @glatard on Mattermost, NIfTI images (`sub-032633/ses-001/anat/sub-032633_ses-001_run-1_space-MNI152NLin2009cAsym_desc-preproc_T1w.nii.gz`) are being produced with identical uncompressed contents but different compressed checksums. This is almost certainly the mtime being set because NIfTI images are being written by nibabel in this section:

https://github.com/nipreps/niworkflows/blob/11ac7a18a403af717c0c2a29a33b7cadb75eabd7/niworkflows/interfaces/bids.py#L579-L644

I would suggest we move to the following approach:

```Python
img = None
if <detect need to modify header>:
    img = <create img>

if img is not None:
    <write img deterministically>
else:
    <copy file with gzip cleaning>
```

This is an LTS-affecting bug, so any fix should target niworkflows 1.3.4.

**Comment by ltetrel** [comment]
This solution https://github.com/nipy/nibabel/issues/1023#issuecomment-861731372 could actually make the non-deterministic file checksum a non-issue.
lmk @effigies

**Comment by effigies** [comment]
Yes, if you want to use `tail -c 8` as a check, that seems fine to me. I still think that a deterministic checksum is a good idea.
