### ISSUE TITLE
Matplotlib constraint

### ISSUE THREAD

**Issue by effigies** [nipreps/niworkflows#667]
@oesteban Just want to check in before updating all the projects...

Niworkflows is constrained here to `~=3.3.1`, but in downstream projects as `>=2.2.0` (or similar). Is there a reason that we're stuck in the `3.3.x` series? Should we do `~=3.3` everywhere so that we only avoid an API-breaking 4.0 bump?

**Comment by effigies** [comment]
The problem I was seeing was actually a problem with using `python setup.py` directly (nipreps/smriprep#270), but it seems like a good idea to do this consistently.

**Comment by oesteban** [comment]
@mgxd was stuck with this too. It's probably safe to pin ~= 3.3 and make everyone's life easier
