### ISSUE TITLE
Unit test broken

### ISSUE THREAD

**Issue by oesteban** [nipreps/niworkflows#742]
It seems our nightly builds have caught a problem with one test:

```Text
=========================== short test summary info ============================
FAILED niworkflows/tests/test_viz.py::test_cifti_surfaces_plot - ValueError: ...
===== 1 failed, 352 passed, 35 skipped, 104 warnings in 469.94s (0:07:49) ======
```

**Comment by effigies** [comment]
Surfplot seems unmaintained, and the dependency on vtk means I've just spent an hour trying to get it working locally and failing. It may be worth finding an alternative plotting tool that only depends on matplotlib.

**Comment by oesteban** [comment]
I don't know what nilearn is using, but finding something without vtk will be hard.

**Comment by effigies** [comment]
Nilearn uses matplotlib or plotly as a backend. I think we should probably switch to that.

**Comment by effigies** [comment]
I've fiddled a bit with adapting the current code. It should be too hard.

**Comment by mgxd** [comment]
I'm +1 to switching to a VTK-less approach, assuming that it won't take a substantial amount of time.

**Comment by danjgale** [comment]
@effigies I haven't been able to seriously sit down and work on surfplot in the last several months for reasons (read: finished phd), but that should change in the coming weeks. So, a pause in maintenance. It's true that surfplot depends on vtk, and I would like to figure out how to include documentation on dealing with that limitation of surfplot

**Comment by effigies** [comment]
@danjgale We switched to nilearn + matplotlib in #745. My understanding was that VTK was being used in brainspace as an alternative to nibabel/nilearn, not matplotlib. I think matplotlib was still ultimately the renderer.
