### ISSUE TITLE
Allow custom configurations in DerivativesDataSink

### ISSUE THREAD

**Issue by tsalo** [nipreps/niworkflows#757]
As far as I can tell, classes that inherit from `DerivativesDataSink` cannot override the entities and path patterns from `data/nipreps.json` without copying the `DerivativesDataSink` source code. It would be great if those variables were set in such a way that they could be overridden in derived classes, like how `out_path_base` is handled.

**Comment by effigies** [comment]
Agreed. Care to submit a PR? (Apologies for the slow response...)

**Comment by tsalo** [comment]
Happy to take a crack at it!
