### ISSUE TITLE
DerivativesDataSink does not extract entities from custom configuration

### ISSUE THREAD

**Issue by tsalo** [nipreps/niworkflows#776]
As of 1.7.1, `DerivativesDataSink` only extracts entities present in the default pybids configurations from the `source_file`. This means that any custom entities defined in the `_config_entities` attribute of the `DerivativesDataSink` are ignored.

I think the relevant part of the code is:

https://github.com/nipreps/niworkflows/blob/1555d2b117d232654e6bd011813fb1767bd88ab6/niworkflows/interfaces/bids.py#L551-L555

Currently, `parse_file_entities` accepts `entities` and `config` options, so I think `DerivativesDataSink` could feed the custom configuration info into the `parse_file_entities` call.

I don't know if it's worth it to fix this with the current version of pybids, given the work being done in https://github.com/bids-standard/pybids/pull/926.

**Comment by effigies** [comment]
I'm fine with making sure that we pass values from the config. I don't know how complicated moving niworkflows over to the ANCP-BIDS backend will be, even if that finishes quickly.

**Comment by tsalo** [comment]
I can open a PR to pass along the configuration info. I'm sure the ANCP-BIDS refactor is going to be a massive endeavor, and if you think it'll be a while before you tackle it, then I agree that addressing it with the current version of pybids is worth it.

**Comment by effigies** [comment]
Yeah, it would be nice to sprint on it again. Unlikely before mid-Feb.
